### PR TITLE
fix(typescript): use export declare const instead

### PR DESCRIPTION
**Pull request by fisherjacobc**
I believe that it is better practice to use `export declare const` instead for the declaration files, since there isn't a value assigned to it.

I saw it in #71 and thought I could help out since it's a simple fix

### CODE REVIEW

**Comment by sasial-dev** [comment]
Thank you so much for helping out!
So here's the deal - we're currently undergoing a rewrite of zap (see `rewrite` branch). And, as this isn't a bug - I don't believe it's worth backporting this fix to the `0.6.x` branch.

**Comment by sasial-dev** [comment]
I was going to rebase your PR to fit into `0.6.4`, but I do not have permission to do so. You're more than welcome to rebase it yourself  after fetching down the branch (`git rebase -i 0.6.x`, and then drop all commits but the one you made) and then I'll merge it in/

**Comment by fisherjacobc** [comment]
If you want to go ahead and do it, that might be easier so I don't mess something up. You should have write permissions now.

**Comment by sasial-dev** [comment]
It still doesn't seem to give me permisison. Might be eaisier to just take your diff from https://github.com/red-blox/zap/pull/76/commits/a9856a33286ad1d02f6d5743eb7bc5a7ac5ea438 and send another PR based on the `0.6.x` branch.

**Comment by fisherjacobc** [comment]
Refer to #103

**Pull request closed without merging**
