### PR TITLE
Add function return types to client emit

### PR DESCRIPTION
**Pull request by Ketasaja**
[Reported](https://discord.com/channels/385151591524597761/1064606584430411906/1266472145559486494) by @crystalflxme in [ROSS](https://discord.gg/qpgNftpnpf).

### CODE REVIEW

**Review by sasial-dev — APPROVED** [review]
Thank you!
(and CI works 🎉 )

Before I merge - are there any other places missing types?

**Comment by Ketasaja** [comment]
> Before I merge - are there any other places missing types?

I forgot TypeScript.

**Comment by Ketasaja** [comment]
> Before I merge - are there any other places missing types?

I don't think so, for this.

**Comment by sasial-dev** [comment]
I reverted this commit - please send another PR after seeing the [issues](https://discord.com/channels/385151591524597761/1064606584430411906/1266568710907236392) @jackdotink mentioned.

**Pull request merged**
