### PR TITLE
Add DateTime types

### PR DESCRIPTION
**Pull request by gaymeowing**
Adds in DateTime and DateTimeMillis as types, with DateTime sending the UnixTimestamp property of the DateTime object, and DateTimeMillis sending the UnixTimestampMillis property of the DateTime object.

### CODE REVIEW

**Review by sasial-dev — COMMENTED** [review]
I'm pretty happy with the code. I just would like you to confirm - what's the motivation between adding two DateTime types? I definitely think we'll keep it, just want to make sure we're on the same wavelength!

**Comment by gaymeowing** [comment]
> I'm pretty happy with the code. I just would like you to confirm - what's the motivation between adding two DateTime types? I definitely think we'll keep it, just want to make sure we're on the same wavelength!

Mainly because sometimes using milliseconds is desired over seconds for cases where the extra accuracy is needed

**Review by sasial-dev — CHANGES_REQUESTED** [review]
Please add the types to be matched in `parser/convert.rs` to at L416 (under `SyntaxTyKind::Ref`).

**Review by sasial-dev — APPROVED** [review]
LGTM!

**Pull request merged**
