### PR TITLE
Clarify enum documentation

### PR DESCRIPTION
**Pull request by ATK422**
Simple docs change to help clarify how to decalre an enum

### CODE REVIEW

**Review by sasial-dev — CHANGES_REQUESTED** [review]
Thank you for this! Can you go through the whole file and add any others that are missing to improve clarity?

**Comment by sasial-dev** [comment]
I'm just going to go ahead and merge this as you didn't respond.

**Comment by ATK422** [comment]
Oh I'm sorry, I saw the requested changes when I was about to sleep and just forgot about it, I can do the rest when I get home. If there's any specific sections that you want me to do, then let me know.

**Comment by sasial-dev** [comment]
No stress - did you get see my ping in Discord? It's not a biggy so don't worry about doing the rest of them!

**Comment by ATK422** [comment]
Thank you, I have mentions silenced by default when I join a server so I didn't, sorry.

**Pull request merged**
